'use client';

import { useState, useEffect } from 'react';
import { TrendingUp, TrendingDown, DollarSign, BarChart3, Calendar, Play, Pause, ExternalLink, MessageSquare, Sparkles } from 'lucide-react';

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? '';

// Matches schemas.FinancialSummaryOut on the backend
interface SectorPerformance {
  id: number;
  sector_name: string;
  performance_percentage: string;
  is_positive: boolean;
}

interface FinancialSummary {
  id: number;
  report_date: string;
  summary_text: string;
  market_tone: string;
  source_urls: string | null;
  created_at: string;
  sectors: SectorPerformance[];
}

const eodData = {
  date: 'February 25, 2026',
  marketSummary: {
    sp500: { value: 5247.81, change: 64.12, percent: 1.24 },
    dow: { value: 43892.55, change: 378.45, percent: 0.87 },
    nasdaq: { value: 16421.33, change: -71.24, percent: -0.43 },
  },
  topGainers: [
    { symbol: 'NVDA', name: 'NVIDIA Corp', price: 782.45, change: 8.67 },
    { symbol: 'TSLA', name: 'Tesla Inc', price: 245.78, change: 6.23 },
    { symbol: 'AMD', name: 'Advanced Micro Devices', price: 167.89, change: 5.45 },
  ],
  topLosers: [
    { symbol: 'META', name: 'Meta Platforms', price: 412.34, change: -4.12 },
    { symbol: 'NFLX', name: 'Netflix Inc', price: 567.23, change: -3.89 },
    { symbol: 'GOOGL', name: 'Alphabet Inc', price: 156.78, change: -2.67 },
  ],
  sectorPerformance: [
    { name: 'Technology', change: 1.45, isPositive: true },
    { name: 'Healthcare', change: 0.89, isPositive: true },
    { name: 'Financials', change: 0.67, isPositive: true },
    { name: 'Energy', change: -0.34, isPositive: false },
    { name: 'Consumer Discretionary', change: -0.78, isPositive: false },
  ],
};

const articleSources = [
  {
    title: 'Stocks Rise as Tech Rally Continues',
    source: 'Wall Street Journal',
    link: 'https://www.wsj.com',
  },
  {
    title: 'Fed Signals Steady Interest Rate Policy',
    source: 'Wall Street Journal',
    link: 'https://www.wsj.com',
  },
  {
    title: 'Energy Sector Faces Headwinds',
    source: 'Wall Street Journal',
    link: 'https://www.wsj.com',
  },
];

export function EODReport() {
  const [liveUpdates, setLiveUpdates] = useState<FinancialSummary[]>([]);
  const [loading, setLoading] = useState(true);

  // Pull the most-recent financial summaries from the backend (Supabase via app.py)
  useEffect(() => {
    let cancelled = false;
    fetch(`${API_URL}/financial-summaries?limit=4`)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data: FinancialSummary[]) => {
        if (!cancelled) setLiveUpdates(data);
      })
      .catch((err) => {
        console.error('Failed to load financial summaries:', err);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  // Format the row's created_at into the existing '16:00 EST' look
  const formatTime = (iso: string): string => {
    try {
      const d = new Date(iso);
      const hhmm = d.toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
        timeZone: 'America/New_York',
      });
      return `${hhmm} EST`;
    } catch {
      return iso;
    }
  };

  // Each card opens the backend-rendered archive (top 5 from DB)
  const reportsArchiveHref = `${API_URL}/test_reports.html`;

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-4">
          <div>
            <div className="flex items-center space-x-2 mb-2">
              <h1 className="text-3xl sm:text-4xl font-bold text-gray-900">
                End of Day Report
              </h1>
            </div>
            <p className="text-gray-600 mb-2">
              AI-Powered Summary from Wall Street Journal Articles
            </p>
            <div className="flex items-center space-x-2 text-gray-600">
              <Calendar className="w-5 h-5" />
              <span>{eodData.date}</span>
            </div>
          </div>
          <div className="mt-4 sm:mt-0">

          </div>
        </div>

        {/* Info Banner */}
        {/* <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 flex items-start space-x-3">
          <BarChart3 className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
          <div className="flex-1">
            <p className="text-sm text-blue-900">
              This report is automatically generated by analyzing and summarizing articles from The Wall Street Journal.
              Use this information as a starting point for discussion in our community forum.
            </p>
          </div>
        </div> */}
      </div>

      {/* Market Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-gray-700">S&P 500</h3>
            <TrendingUp className="w-5 h-5 text-green-600" />
          </div>
          <div className="text-3xl font-bold text-gray-900 mb-2">
            {eodData.marketSummary.sp500.value.toLocaleString()}
          </div>
          <div className="flex items-center space-x-2">
            <span className="text-green-600 font-medium">
              +{eodData.marketSummary.sp500.change}
            </span>
            <span className="text-green-600 font-medium">
              ({eodData.marketSummary.sp500.percent}%)
            </span>
          </div>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-gray-700">Dow Jones</h3>
            <TrendingUp className="w-5 h-5 text-green-600" />
          </div>
          <div className="text-3xl font-bold text-gray-900 mb-2">
            {eodData.marketSummary.dow.value.toLocaleString()}
          </div>
          <div className="flex items-center space-x-2">
            <span className="text-green-600 font-medium">
              +{eodData.marketSummary.dow.change}
            </span>
            <span className="text-green-600 font-medium">
              ({eodData.marketSummary.dow.percent}%)
            </span>
          </div>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-gray-700">NASDAQ</h3>
            <TrendingDown className="w-5 h-5 text-red-600" />
          </div>
          <div className="text-3xl font-bold text-gray-900 mb-2">
            {eodData.marketSummary.nasdaq.value.toLocaleString()}
          </div>
          <div className="flex items-center space-x-2">
            <span className="text-red-600 font-medium">
              {eodData.marketSummary.nasdaq.change}
            </span>
            <span className="text-red-600 font-medium">
              ({eodData.marketSummary.nasdaq.percent}%)
            </span>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Live Updates Stream */}
        <div className="lg:col-span-2 space-y-6">
          <div>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <BarChart3 className="w-6 h-6 text-gray-700" />
                <h2 className="text-2xl font-bold text-gray-900">End of Day Summary</h2>
              </div>
              <a
                href="/forum"
                className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium"
              >
                <MessageSquare className="w-4 h-4" />
                <span>Discuss in Forum</span>
              </a>
            </div>
            <div className="bg-white rounded-xl border border-gray-200 divide-y divide-gray-200">
              {loading ? (
                <p className="p-6 text-gray-500 text-sm">Loading latest updates…</p>
              ) : liveUpdates.length === 0 ? (
                <p className="p-6 text-gray-500 text-sm">No updates available right now.</p>
              ) : (
                liveUpdates.map((update) => {
                  const timeStr = formatTime(update.created_at);
                  const tone = update.market_tone || 'Neutral';
                  return (
                    <a
                      key={update.id}
                      href={reportsArchiveHref}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block p-6 hover:bg-gray-50 transition-colors"
                    >
                      <div className="flex items-start space-x-4">
                        <div className="flex-shrink-0">
                          <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center">
                            <span className="text-blue-600 font-semibold text-sm">{timeStr.split(':')[0]}:{timeStr.split(':')[1].split(' ')[0]}</span>
                          </div>
                        </div>
                        <div className="flex-1">
                          <div className="flex items-center justify-between mb-2">
                            <div className="text-sm font-medium text-gray-500">{timeStr}</div>
                            <span className="text-xs text-blue-600 font-medium capitalize">{tone}</span>
                          </div>
                          <p className="text-gray-800">{update.summary_text}</p>
                        </div>
                      </div>
                    </a>
                  );
                })
              )}
            </div>
          </div>

          {/* Source Articles */}
          <div>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Source Articles</h2>
            <div className="bg-white rounded-xl border border-gray-200 divide-y divide-gray-200">
              {articleSources.map((article, index) => (
                <a
                  key={index}
                  href={article.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="block p-4 hover:bg-gray-50 transition-colors"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex-1">
                      <h3 className="font-semibold text-gray-900 mb-1">{article.title}</h3>
                      <p className="text-sm text-gray-600">{article.source}</p>
                    </div>
                    <ExternalLink className="w-5 h-5 text-gray-400 flex-shrink-0 ml-3" />
                  </div>
                </a>
              ))}
            </div>
            <p className="text-xs text-gray-500 mt-3">
              Click to read the full articles on The Wall Street Journal website
            </p>
          </div>

          {/* Sector Performance */}
          <div>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Sector Performance</h2>
            <div className="bg-white rounded-xl border border-gray-200 p-6">
              <div className="space-y-4">
                {eodData.sectorPerformance.map((sector, index) => (
                  <div key={index} className="flex items-center justify-between">
                    <span className="text-gray-700 font-medium">{sector.name}</span>
                    <div className="flex items-center space-x-2">
                      {sector.isPositive ? (
                        <>
                          <TrendingUp className="w-4 h-4 text-green-600" />
                          <span className="text-green-600 font-semibold">+{sector.change}%</span>
                        </>
                      ) : (
                        <>
                          <TrendingDown className="w-4 h-4 text-red-600" />
                          <span className="text-red-600 font-semibold">{sector.change}%</span>
                        </>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          {/* Top Gainers */}
          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-4">Top Gainers</h2>
            <div className="bg-white rounded-xl border border-gray-200 divide-y divide-gray-200">
              {eodData.topGainers.map((stock, index) => (
                <div key={index} className="p-4">
                  <div className="flex items-center justify-between mb-1">
                    <div>
                      <div className="font-semibold text-gray-900">{stock.symbol}</div>
                      <div className="text-xs text-gray-500">{stock.name}</div>
                    </div>
                    <TrendingUp className="w-5 h-5 text-green-600" />
                  </div>
                  <div className="flex items-center justify-between mt-2">
                    <span className="text-gray-900 font-medium">${stock.price}</span>
                    <span className="text-green-600 font-semibold">+{stock.change}%</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Top Losers */}
          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-4">Top Losers</h2>
            <div className="bg-white rounded-xl border border-gray-200 divide-y divide-gray-200">
              {eodData.topLosers.map((stock, index) => (
                <div key={index} className="p-4">
                  <div className="flex items-center justify-between mb-1">
                    <div>
                      <div className="font-semibold text-gray-900">{stock.symbol}</div>
                      <div className="text-xs text-gray-500">{stock.name}</div>
                    </div>
                    <TrendingDown className="w-5 h-5 text-red-600" />
                  </div>
                  <div className="flex items-center justify-between mt-2">
                    <span className="text-gray-900 font-medium">${stock.price}</span>
                    <span className="text-red-600 font-semibold">{stock.change}%</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
