"""update sector_performance table

Revision ID: 4d9b92176b58
Revises: aa0241b493b7
Create Date: 2026-05-17 00:40:00.005225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d9b92176b58'
down_revision: Union[str, Sequence[str], None] = 'aa0241b493b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_sources_id'), table_name='summary_sources')
    op.drop_table('summary_sources')
    op.alter_column('blacklist', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('blacklist', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('financial_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('reporting_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('sector_performance', sa.Column('report_date', sa.String(), nullable=False))
    op.add_column('sector_performance', sa.Column('summary_text', sa.Text(), nullable=False))
    op.add_column('sector_performance', sa.Column('market_tone', sa.String(), nullable=False))
    op.add_column('sector_performance', sa.Column('source_urls', sa.Text(), nullable=True))
    op.add_column('sector_performance', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'sector_performance', ['report_date'])
    op.drop_constraint(op.f('sector_performance_summary_id_fkey'), 'sector_performance', type_='foreignkey')
    op.drop_column('sector_performance', 'is_positive')
    op.drop_column('sector_performance', 'summary_id')
    op.alter_column('threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('threads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('threads', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('sector_performance', sa.Column('summary_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sector_performance', sa.Column('is_positive', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sector_performance_summary_id_fkey'), 'sector_performance', 'financial_summaries', ['summary_id'], ['id'])
    op.drop_constraint(None, 'sector_performance', type_='unique')
    op.drop_column('sector_performance', 'created_at')
    op.drop_column('sector_performance', 'source_urls')
    op.drop_column('sector_performance', 'market_tone')
    op.drop_column('sector_performance', 'summary_text')
    op.drop_column('sector_performance', 'report_date')
    op.alter_column('reports', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reporting_flags', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('financial_summaries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('comments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('blacklist', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('blacklist', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('summary_sources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['financial_summaries.id'], name=op.f('summary_sources_summary_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('summary_sources_pkey'))
    )
    op.create_index(op.f('ix_summary_sources_id'), 'summary_sources', ['id'], unique=False)
    # ### end Alembic commands ###
