"""update sector_performance table

Revision ID: fa48876a55f4
Revises: 4d9b92176b58
Create Date: 2026-05-17 00:45:31.204535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa48876a55f4'
down_revision: Union[str, Sequence[str], None] = '4d9b92176b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sector_performance', 'market_tone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sector_performance', sa.Column('market_tone', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
